trusted_manufacturers = (
      ('0', 'DELL'),
      ('1', 'LENOVO'),
      ('2', 'ASUS'),
      ('3', 'APPLE'),
      ('4', 'ACER'),
      ('5', 'HP'),
      ('6', 'HEWLETT PACKARD'),
      ('7', 'VAIO'),
      ('8', 'CORSAIR'),
      ('9', 'GIGABYTE'),
      ('10', 'GOOGLE'),
      ('11', 'LG'),
      ('12', 'MICROSOFT'),
      ('13', 'ORIGIN PC'),
      ('14', 'SAMSUNG'),
      ('15', 'ZEBRONICS'),
      ('16', 'TOSHIBA'),
      ('17', 'DYNABOOK'),
      ('18', 'CISCO'),
      ('19', 'IBM'),
      ('20', 'FUJITSU'),
      ('21', 'ORACLE'),
      ('22', 'NEC'),
      ('23', 'WIPRO')
)
