# Generated by Django 5.1.2 on 2024-11-25 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assettype', models.CharField(help_text='Laptop / desktop etc', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=15, null=True)),
                ('snum', models.TextField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a hw Model', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.location')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialn', models.CharField(blank=True, help_text="Device's Serial Number", max_length=100, verbose_name='S/N')),
                ('datacenter', models.CharField(default='sec-62 Noida', help_text='Data Center', max_length=50, verbose_name='DataCenter')),
                ('hostname', models.CharField(max_length=100, null=True, verbose_name='Hostname')),
                ('rack', models.CharField(max_length=50, null=True, verbose_name='Rack')),
                ('lob', models.CharField(max_length=50, null=True, verbose_name='LOB')),
                ('ip', models.CharField(max_length=20, null=True, verbose_name='IP Address')),
                ('mgmt_ilo_ip', models.CharField(max_length=20, null=True, verbose_name='Management ILO IP')),
                ('po_number', models.CharField(max_length=50, null=True, verbose_name='Purchase Number')),
                ('po_date', models.DateField(blank=True, null=True, verbose_name='Purchase date')),
                ('invoice_number', models.CharField(max_length=50, null=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice date')),
                ('mih_number', models.CharField(help_text='Manfucturer Identification Number', max_length=50, null=True, verbose_name='MIH Number')),
                ('project_name', models.TextField(blank=True, help_text='MIH Project Number', max_length=1000, null=True)),
                ('warranty_start_date', models.DateField(null=True, verbose_name='Warranty Start Date')),
                ('warranty_expiration_date', models.DateField(blank=True, null=True, verbose_name='Warranty End Date')),
                ('amc_expiration_date', models.DateField(blank=True, null=True, verbose_name='AMC Expiration Date')),
                ('tracking_number', models.CharField(max_length=50, null=True, verbose_name='IR/MO  Number')),
                ('status', models.CharField(blank=True, choices=[('0', 'Received'), ('1', 'Deployed'), ('2', 'Inactive'), ('3', 'In Stock'), ('4', 'Decommission'), ('5', 'Disposed')], default='0', help_text='Asset Status', max_length=1, verbose_name='Asset Status')),
                ('substatus', models.CharField(blank=True, choices=[('0', 'Completed Shipment'), ('1', 'Functional'), ('2', 'Not In use'), ('3', 'In Inventory'), ('4', 'Decommissioned'), ('5', 'Disposed')], default='0', help_text='Asset Sub Status', max_length=1, verbose_name='Asset Sub Status')),
                ('eos', models.CharField(help_text='End of Service', max_length=20, null=True, verbose_name='EOS')),
                ('eol', models.CharField(help_text='End of Life', max_length=20, null=True, verbose_name='EOL')),
                ('support_status', models.CharField(help_text='Under warranty or AMC', max_length=20, null=True, verbose_name='Support Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Enter a job description of the Device', max_length=1000, null=True, verbose_name='Remarks or Ticket Number')),
                ('asset_type', models.ForeignKey(help_text='Device Asset Type', on_delete=django.db.models.deletion.PROTECT, to='catalog.assettype')),
                ('assigned_spoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.company')),
                ('location', models.ForeignKey(help_text='Device Location', on_delete=django.db.models.deletion.PROTECT, to='catalog.location')),
                ('oem', models.ForeignKey(help_text='Device Manufacturer', on_delete=django.db.models.deletion.PROTECT, to='catalog.manufacturer', verbose_name='OEM')),
                ('model', models.ForeignKey(help_text='Device Model', on_delete=django.db.models.deletion.PROTECT, to='catalog.model')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(choices=[('1', 'Deploy'), ('2', 'Stock'), ('3', 'Refresh'), ('4', 'Stolen')], default='1', max_length=10, verbose_name='Reason')),
                ('name', models.CharField(max_length=50)),
                ('credate', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cus2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.customer', verbose_name='To')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer', verbose_name='From')),
                ('deptin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.department', verbose_name='Get')),
                ('deptout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.department', verbose_name='Out')),
                ('equip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.device', verbose_name='Device')),
                ('equip1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.device', verbose_name='Device 2')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
