# Generated by Django 5.1.2 on 2024-11-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.AlterField(
            model_name='device',
            name='oem',
            field=models.CharField(choices=[(0, 'DELL'), (1, 'LENOVO'), (2, 'ASUS'), (3, 'APPLE'), (4, 'ACER'), (5, 'HP'), (6, 'HEWLETT PACKARD'), (7, 'VAIO'), (8, 'CORSAIR'), (9, 'GIGABYTE'), (10, 'GOOGLE'), (11, 'LG'), (12, 'MICROSOFT'), (13, 'ORIGIN PC'), (14, 'SAMSUNG'), (15, 'ZEBRONICS'), (16, 'TOSHIBA'), (17, 'DYNABOOK'), (18, 'CISCO'), (19, 'IBM'), (20, 'FUJITSU'), (21, 'ORACLE'), (22, 'NEC'), (23, 'WIPRO')], default='', help_text='HP / DELL / ...', max_length=20, verbose_name='OEM'),
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='cus2',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='deptin',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='deptout',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='equip',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='equip1',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
        migrations.RemoveField(
            model_name='device',
            name='created',
        ),
        migrations.RemoveField(
            model_name='device',
            name='modified',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
