# Generated by Django 5.1.2 on 2024-11-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_device_oem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='datacenter',
        ),
        migrations.AddField(
            model_name='device',
            name='datacenter_location',
            field=models.ForeignKey(default=1, help_text='DataCenter Location', on_delete=django.db.models.deletion.PROTECT, to='catalog.location'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(default='default rack', help_text='Device Location', max_length=50, verbose_name='Location'),
        ),
    ]
